export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'

export const DELETE_PRODUCT_BEGIN = 'DELETE_PRODUCT_BEGIN'

export const TOGGLE_PRODUCT = 'TOGGLE_PRODUCT'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const SHOW_HIDE = 'SHOW_HIDE'
